### ISSUE TITLE
Updating to Julia v1.6

### ISSUE THREAD

**Issue by richardreeve** [boydorr/EcoSISTEM.jl#10]
Julia v1.6-rc1 is now out, so I wonder whether the github workflow will now work with 1.6?

**Comment by claireh93** [comment]
Seems like there are some issues precompiling packages like NetCDF still with 1.6, see: https://github.com/boydorr/Simulation.jl/actions/runs/554273579

**Comment by richardreeve** [comment]
Obviously Julia v1.6 is now out...
